version: "3.8"

services:
  mongodb:
    image: mongo:4.4.24-focal
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network
    ports:
      - "27017:27017"

  server:
    image: houbalinko/taskapp-backend:1.0.1
    depends_on:
      - mongodb
    networks:
      - app_network
    ports:
      - "5003:5003"

  client:
    image: houbalinko/taskapp-frontend:1.0.4
    depends_on:
      - server
    networks:
      - app_network
    ports:
      - "3000:3000"

networks:
  app_network:
    driver: overlay

