version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
    container_name: server
    networks:
      - app_network
    ports:
      - "5003:5003"
    depends_on:
      - mongodb

  client:
    build:
      context: ./client
    container_name: client
    networks:
      - app_network
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://server:5003 # Update this if needed
    depends_on:
      - server

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:

